---
title: "02_Clean_Merge_Cross_States"
output: html_document
---

```{r}
library(tidyverse)
library(gridExtra)
library(lubridate)

states_df <- read.csv(file.path(dropbox_file_path,"Data/google_trends/RawData/brazil_extract_crosstate.csv"), encoding = "UTF-8")
state_pop_data <- read.csv(file.path(dropbox_file_path, "Data/city_population/FinalData/brazil_state_pop.csv"))
admin_data <- read.csv(file.path(dropbox_file_path, "Data/brazil_admin_data/brazil_covid19_200419.csv"), encoding = "UTF-8")
```

```{r}
states_df %>% 
  filter(unit_level == "region") %>% 
  count(keyword)

states_df <- 
  states_df %>% 
  filter(unit_level == "region") %>% 
  mutate(location = str_replace(location, "State of ", "")) %>% 
  rename(state = location)

#removing accents
states_df <-   
  states_df %>% 
  mutate(state_en = stringi::stri_trans_general(state, "Latin-ASCII") %>% str_to_upper())
```



```{r}
admin_data <- 
  admin_data %>% 
  mutate(
    state_en = stringi::stri_trans_general(state, "Latin-ASCII") %>% str_to_upper(), 
    date = as.Date(date)
  ) 

admin_data <- 
  admin_data %>% 
  left_join(
    state_pop_data, 
    by = c("state" = "State")
  )
```



```{r}
states_admin_df <- 
  states_df %>% 
  left_join(
    admin_data, 
    by = c("state" = "state")
  )
```

# We create categories for key words

```{r}
states_admin_df <- 
  states_admin_df %>% 
  mutate(
    categories = case_when(
      keyword %in% 
        c("abuso", "abuso sexual", "desemprego",  "dívida", "Educação online",
          "psicologia", "terapia" ) ~ "consequences",
      keyword %in% 
        c("cama de hospital", "desinfetantes", "hidroxicloroquina", "cloroquina",
          "máscara facial", "termômetros", "ventiladores", "medicos", 
          "profissionais de saúde") ~ "resources",
      keyword %in% 
        c( "dificuldade ao respirar", "dor nos olhos", "falta de cheiro", 
           "febre", "febre alta valor","perda de olfato", "tosse",
           "sintomas do coronavirus", "teste de coronavírus") ~ "symptoms",
      keyword %in% 
        c("distância social","fique em casa", "lavar as mãos", "Isolamento social", 
          "isolamento vertical") ~ "prevention", 
      keyword %in% c("coronavirus", "covid", "ajuda do coronavírus") ~ "virus", 
      keyword %in% 
        c("como tratar o coronavírus", "Estou com falta de ar",
        "estou com febre", "Eu fico em casa", "eu tenho coronavírus",
        "Perdi o olfato", "quais são os sintomas do coronavírus", "volta brasil"
        ) ~ "in_1st_person"
      )
  )
```

# Create new variables: death rate, cases & deaths per 100,000

```{r}
states_admin_df <- 
  states_admin_df %>% 
  mutate(
    case_rate = cases*100000/estimate_2018_state, 
    death_rate = deaths*100000/estimate_2018_state, 
    fatalities_per_case = deaths/cases
  )

states_admin_df <- 
  states_admin_df %>% 
  mutate(fatalities_per_case = if_else(is.na(fatalities_per_case), 0, fatalities_per_case))
```

Export

```{r}
saveRDS(states_admin_df, file.path(dropbox_file_path, "Data/google_trends/FinalData/brazil_crosstates_clean.Rds"))
write.csv(states_admin_df, file.path(dropbox_file_path, "Data/google_trends/FinalData/brazil_crosstates_clean.csv"), row.names = F)
```

