---
title: "04_creating_variables_data"
author: Manuel Ramos
output: html_document
---

```{r, include = FALSE}
trends_df <- read.csv(file.path(dropbox_file_path, "Data/google_trends/FinalData/brazil_admin_trends_clean.csv"))
```

# Cleaning and creation of new variables
```{r}
trends_df <- trends_df %>% mutate(date = as.Date(date))
```

# We create categories for key words

```{r}
trends_df <- 
  trends_df %>% 
  mutate(
    categories = case_when(
      keyword %in% 
        c("abuso", "abuso sexual", "desemprego",  "dívida", "Educação online",
          "psicologia", "terapia" ) ~ "consequences",
      keyword %in% 
        c("cama de hospital", "desinfetantes", "hidroxicloroquina", "cloroquina",
          "máscara facial", "termômetros", "ventiladores", "medicos", 
          "profissionais de saúde") ~ "resources",
      keyword %in% 
        c( "dificuldade ao respirar", "dor nos olhos", "falta de cheiro", 
           "febre", "febre alta valor","perda de olfato", "tosse",
           "sintomas do coronavirus", "teste de coronavírus") ~ "symptoms",
      keyword %in% 
        c("distância social","fique em casa", "lavar as mãos", "Isolamento social", 
          "isolamento vertical") ~ "prevention", 
      keyword %in% c("coronavirus", "covid", "ajuda do coronavírus") ~ "virus", 
      keyword %in% 
        c("como tratar o coronavírus", "Estou com falta de ar",
        "estou com febre", "Eu fico em casa", "eu tenho coronavírus",
        "Perdi o olfato", "quais são os sintomas do coronavírus", "volta brasil"
        ) ~ "in_1st_person"
      )
  )
```

# Create new variables: death rate, cases & deaths per 100,000

```{r}
trends_df <- 
  trends_df %>% 
  mutate(
    case_rate = cases*100000/estimate_2018_state, 
    death_rate = deaths*100000/estimate_2018_state, 
    fatalities_per_case = deaths/cases
  )

trends_df <- 
  trends_df %>% 
  mutate(fatalities_per_case = if_else(is.na(fatalities_per_case), 0, fatalities_per_case))
```


# Saving the data
```{r, include = FALSE}
write.csv(trends_df, file.path(dropbox_file_path, "Data/google_trends/FinalData/brazil_trends_clean_final.csv"), row.names = F)
```
