---
title: "Dashboard Searches"
runtime: shiny
output: html_document
---

```{r include=FALSE}
library(tidyverse)
library(gridExtra)
library(shinydashboard)
library(dashboardthemes)

#trends_df <- read.csv(file.path(dropbox_file_path, "Data/google_trends/FinalData/brazil_trends_clean_final.csv"))

trends_df <- read.csv("/Users/wb537287/Dropbox/COVID Social Media Analysis/Data/google_trends/FinalData/brazil_trends_clean_final.csv")

trends_df <- trends_df %>% mutate(date = as.Date(date))

trends_df <- trends_df %>% mutate(state = as.character(state))
```

Searches by State {data-navmenu="State Trends"}
=====================================

```{r echo=FALSE}
states_name <-
  trends_df %>%
  count(state) %>%
  filter(!state %in% c("Santa Catarina", "Rondônia", NA)) %>%
  pull(state)

ui <- dashboardPage(
  dashboardHeader(
    title = h3("Brazil Terms Dashboard")
  ),
  dashboardSidebar(
    selectInput(
      inputId = 'state',
      label = 'State',
      choices = states_name,
      selected = "Acre"
      )
    ),
  dashboardBody(
    plotOutput('plotName'), 
    shinyDashboardThemes(theme = "blue_gradient")
  )
)

server <- function(input, output) {
  dataset <- reactive({
      trends_df %>%
      filter(!is.na(categories), categories != "consequences") %>%
      group_by(categories, state, date) %>%
      mutate(mean_hits = mean(hits, na.rm = TRUE)) %>%
      ungroup()
  })

  output$plotName <- renderPlot({
      dataset() %>%
      filter(state == input$state)  %>%
      ggplot() +
      geom_line(aes(date, mean_hits, group = categories, color = categories)) +
      geom_line(aes(date, cases)) +
      coord_cartesian(ylim = c(0, 100))
  })
}

shinyApp(ui = ui, server = server)
```

```{r echo=FALSE}
# states_name <- 
#   trends_df %>% 
#   count(state) %>%
#   filter(!state %in% c("Santa Catarina", "Rondônia", NA)) %>% 
#   pull(state)
# 
# ui <- fluidPage(
#   sidebarPanel(
#     selectInput(
#       inputId = 'state', 
#       label = 'State',
#       choices = states_name, 
#       selected = "Acre"
#     ), 
#   mainPanel(
#     plotOutput('plotName')
#   )
#   )
# )
# 
# server <- function(input, output) {
#   dataset <- reactive({
#       trends_df %>% 
#       filter(!is.na(categories), categories != "consequences") %>% 
#       group_by(categories, state, date) %>% 
#       mutate(mean_hits = mean(hits, na.rm = TRUE)) %>% 
#       ungroup()
#   })
#   
#   output$plotName <- renderPlot({ 
#       dataset() %>% 
#       filter(state == input$state)  %>% 
#       ggplot() + 
#       geom_line(aes(date, mean_hits, group = categories, color = categories)) +
#       geom_line(aes(date, cases)) +
#       coord_cartesian(ylim = c(0, 100))
#   }, height = 700, width = 800)
#   
# }
# 
# shinyApp(ui = ui, server = server)
```

